# Generated by Django 6.0.6 on 2026-06-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Otracker',
            fields=[
                ('otrackerid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productview',
            fields=[
                ('productviewid', models.AutoField(primary_key=True, serialize=False)),
                ('productimage1', models.URLField(blank=True, null=True)),
                ('productimage2', models.URLField(blank=True, null=True)),
                ('productimage3', models.URLField(blank=True, null=True)),
                ('productimage4', models.URLField(blank=True, null=True)),
                ('productimage5', models.URLField(blank=True, null=True)),
                ('productimage6', models.URLField(blank=True, null=True)),
                ('productimage7', models.URLField(blank=True, null=True)),
                ('productimage8', models.URLField(blank=True, null=True)),
                ('productimage9', models.URLField(blank=True, null=True)),
                ('productimage10', models.URLField(blank=True, null=True)),
                ('productname', models.CharField(max_length=100)),
                ('producttitle', models.TextField()),
                ('productprice', models.BigIntegerField()),
                ('productmrpprice', models.IntegerField()),
                ('productdiscountrate', models.CharField(max_length=20)),
                ('productsize', models.CharField(max_length=100)),
                ('productsize1', models.CharField(max_length=100)),
                ('productsize2', models.CharField(max_length=100)),
                ('productsize3', models.CharField(max_length=100)),
                ('productcolor1', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor2', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor3', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor4', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor5', models.CharField(blank=True, max_length=20, null=True)),
                ('productrating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('producttophighlights1', models.CharField(max_length=100)),
                ('producttophighlights2', models.CharField(max_length=100)),
                ('producttophighlights3', models.CharField(max_length=100)),
                ('producttophighlights4', models.CharField(max_length=100)),
                ('producttophighlights5', models.CharField(max_length=100)),
                ('producttophighlights6', models.CharField(max_length=100)),
                ('productaboutitem1', models.CharField(max_length=100)),
                ('productaboutitem2', models.CharField(max_length=100)),
                ('productaboutitem3', models.CharField(max_length=100)),
                ('productaboutitem4', models.CharField(max_length=100)),
                ('productaboutitem5', models.CharField(max_length=100)),
                ('productitemdetail1', models.CharField(max_length=100)),
                ('productitemdetail2', models.CharField(max_length=100)),
                ('productitemdetail3', models.CharField(max_length=100)),
                ('productitemdetail4', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productview')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
