# Generated by Django 6.0.6 on 2026-06-18 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem5',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('subtotal', models.IntegerField()),
                ('deliverycharges', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('otracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.otracker')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('productview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productview')),
            ],
        ),
    ]
