# Generated by Django 6.0.6 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
