# Generated by Django 6.0.6 on 2026-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_review_color_review_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
