# Generated by Django 6.0.6 on 2026-06-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_review_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topproduct',
            fields=[
                ('topproductid', models.AutoField(primary_key=True, serialize=False)),
                ('productimage1', models.URLField(blank=True, null=True)),
                ('producttitle', models.TextField()),
                ('product_viewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productview')),
            ],
        ),
    ]
