# Generated by Django 6.0.6 on 2026-06-27 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_productviewcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productviewcount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productviewcount',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='productviewcount',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_user'),
        ),
        migrations.AddConstraint(
            model_name='productviewcount',
            constraint=models.UniqueConstraint(fields=('product', 'session_key'), name='unique_product_session'),
        ),
    ]
